### ISSUE TITLE
error: ‘std::enable_if_t’ has not been declared.

### ISSUE THREAD

**Issue by lhjey** [krzhu/IdeaPlaceEx#1]
Hello, I encountered these problems after configuring the environment, I hope to get help to solve the problem.

running install
    running build
    running build_ext
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
    -- Install prefix: /usr/local
    -- Use system LIMBO /home/lhj/MAGICAL/Limbo/
    -- Boost version: 1.65.1
    -- Found the following Boost libraries:
    --   system
    --   graph
    --   iostreams
    --   regex
    -- Found ZLIB: /usr/local/lib/libz.so (found version "1.2.11")
    -- Find Lemon: /home/lhj/MAGICAL/lemon/
    -- Find Eigen: /home/lhj/MAGICAL/eigen3/
    -- Use system LPSOLVE /home/lhj/MAGICAL/lpsolve/
    -- LPSOLVE_ROOT_DIR = /home/lhj/MAGICAL/lpsolve/
    -- LPSOLVE_LIBRARIES = /home/lhj/MAGICAL/lpsolve/liblpsolve55.so
    -- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot
    -- Use system pybind11: /home/lhj/MAGICAL/pybind11/
    -- pybind11 v2.6.2 dev1
    -- Found PythonInterp: /usr/bin/python (found version "2.7.17")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "3.6.9")
    -- Use system Gurobi /home/lhj/MAGICAL/gurobi911/linux64/
    -- GUROBI_ROOT_DIR = /home/lhj/MAGICAL/gurobi911/linux64/
    -- GUROBI_LIBRARIES = /home/lhj/MAGICAL/gurobi911/linux64/lib/libgurobi_c++.a;/home/lhj/MAGICAL/gurobi911/linux64/lib/libgurobi91.so
    -- Use system wnlib /home/lhj/MAGICAL/wnlib/
    -- Using build type RELEASE
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-QUp6Oy-build/build/temp.linux-x86_64-2.7
    Scanning dependencies of target IdeaPlaceEx
    Scanning dependencies of target IdeaPlaceExPy

Problem 1:
 [  6%] Building CXX object CMakeFiles/IdeaPlaceEx.dir/src/db/Parameters.cpp.o
    In file included from /tmp/pip-QUp6Oy-build/src/place/NlpGPlacer.h:18:0,
                     from /tmp/pip-QUp6Oy-build/src/main/IdeaPlaceEx.h:14,
                     from /tmp/pip-QUp6Oy-build/src/api/IdeaPlaceExAPI.cpp:10:
/src/place/nlp/nlpOuterOptm.hpp:262:70: error: ‘std::enable_if_t’ has not been declared
                     template<typename nlp_type, typename mult_type, std::enable_if_t<nlp::is_first_order_diff<nlp_type>::value, void>* = nullptr>
                                                                          ^~~~~~~~~~~
    /tmp/pip-QUp6Oy-build/src/place/nlp/nlpOuterOptm.hpp:262:81: error: expected ‘>’ before ‘<’ token
                     template<typename nlp_type, typename mult_type, std::enable_if_t<nlp::is_first_order_diff<nlp_type>::value, void>* = nullptr>
                                                                                     ^

Problem 2:
/src/place/NlpGPlacer.h:516:25: error: expected primary-expression before ‘auto’
             static decltype(auto) inverse(matrix_type &matrix)
                             ^~~~
    /tmp/pip-QUp6Oy-build/src/place/NlpGPlacer.h:516:25: error: expected ‘)’ before ‘auto’
    /tmp/pip-QUp6Oy-build/src/place/NlpGPlacer.h:516:25: error: expected primary-expression before ‘auto’
    /tmp/pip-QUp6Oy-build/src/place/NlpGPlacer.h:516:25: error: expected primary-expression before ‘auto’
    /tmp/pip-QUp6Oy-build/src/place/NlpGPlacer.h:516:25: error: expected primary-expression before ‘auto’
    /tmp/pip-QUp6Oy-build/src/place/NlpGPlacer.h:516:25: error: expected primary-expression before ‘auto’
    /tmp/pip-QUp6Oy-build/src/place/NlpGPlacer.h:516:16: error: expected unqualified-id before ‘decltype’
             static decltype(auto) inverse(matrix_type &matrix)
                    ^~~~~~~~
    /tmp/pip-QUp6Oy-build/src/place/NlpGPlacer.h:530:25: error: expected primary-expression before ‘auto’
             static decltype(auto) inverse(matrix_type &matrix)
                             ^~~~

Problem 3:
[ 51%] Linking CXX executable ../../bin/IdeaPlaceEx
    CMakeFiles/IdeaPlaceEx.dir/src/parser/ParserGds.cpp.o: In function `IDEAPLACE::ParserCellGds::parseCellGds(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)':
    ParserGds.cpp:(.text+0xdc5): undefined reference to `GdsParser::GdsDB::GdsDB::GdsDB()'
    ParserGds.cpp:(.text+0xdd3): undefined reference to `vtable for GdsParser::GdsDB::GdsReader'
    ParserGds.cpp:(.text+0xe6c): undefined reference to `GdsParser::GdsDB::GdsReader::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

**Comment by krzhu** [comment]
For the problem 1 and 2, the compiler is complaining about C++14 syntax. I think it should be fine with g++ 7.5. But I don't know about case. Can you double check with your compiler's C14 support and maybe try recent g++/clang++ versions?

For the problem 3, the GdsParser classes are from Limbo library. They are linked with static libraries built with the Limbo library. Can you check whether they are correctly linked (see https://github.com/krzhu/IdeaPlaceEx/blob/501a1f2d583928846fa1b6b524c17bfe789d1f87/CMakeLists.txt#L134)

Thanks

**Comment by lhjey** [comment]
Thank you for your advice, the above problem has been resolved. However, there is a new problem. I tried adding "-fPIC" to FLAGS, and the error still exists. I don't know if the FLAGS position was added incorrectly.
![image](https://user-images.githubusercontent.com/49546927/103512089-1f7f3c00-4ea3-11eb-9938-f316b8984ba5.png)

**Comment by krzhu** [comment]
> Thank you for your advice, the above problem has been resolved. However, there is a new problem. I tried adding "-fPIC" to FLAGS, and the error still exists. I don't know if the FLAGS position was added incorrectly.
> ![image](https://user-images.githubusercontent.com/49546927/103512089-1f7f3c00-4ea3-11eb-9938-f316b8984ba5.png)

Yeah. It'd better to be removed. wnlib is not being used right now.

I have push a new branch (https://github.com/krzhu/IdeaPlaceEx/tree/nownlib) and a PR (https://github.com/krzhu/IdeaPlaceEx/pull/3) You can try out the new branch for now.  It would be great if you can give some feedback... I will do some testing this week and then merge the branch into the master.

Thanks for pointing out the issue.

**Comment by lhjey** [comment]
I tried it according to your modification, the error has been eliminated and the make is successful. thanks for your suggestions.

**Comment by krzhu** [comment]
Close.
